import type { NextPage } from 'next';
import Head from 'next/head';
import classes from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <div className={classes.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/css2?family=Abel&display=swap" rel="stylesheet"></link>
      </Head>

      <main className={classes.main}>
        Home Page
      </main>
    </div>
  )
}

export default Home;
